apps/store/urls.py
from django.urls import path

from .views import IndexView

app_name = "store"

urlpatterns = [
    path(
        route="",
        view=IndexView.as_view(),
        name="index",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("apps.store.urls", namespace="store")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("products/", include("apps.products.urls", namespace="products")),
    path("cart/", include("apps.cart.urls", namespace="cart")),
    path("orders/", include("apps.orders.urls", namespace="orders")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path(
            route="400/",
            view=default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            route="403/",
            view=default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            route="404/",
            view=default_views.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path(
            route="500/",
            view=default_views.server_error,
        ),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

templates/403_csrf.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {% trans "Forbidden (403)" %}
{% endblock title %}
{% block content %}
  <section class="container py-12">
    <div class="row justify-content-center">
      <div class="col-lg-7 col-sm-10">
        <div class="vstack align-items-center gap-6">
          <h1 class="display-5">
            {% trans "Forbidden (403)" %}
          </h1>
          <p class="fs-lg">
            {% if exception %}
              {{ exception }}
            {% else %}
              {% trans "You're not allowed to access this page." %}
            {% endif %}
          </p>
          <a href="{% url 'store:index' %}" class="btn btn-lg btn-primary">
            {% trans "Go to homepage" %}
          </a>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/base.html
{% load i18n %}
{% load static %}
{% load django_htmx %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}" data-bs-theme="light">
  <head>
    <title>
      {% block title %}
        {{ page_title|default:_("Welcome!") }}
      {% endblock title %}
      | Elastómeros Ecuatorianos
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Elastómeros Ecuatorianos online store" />
    <meta name="author" content="Dennis Paz" />
    <link href="{% static 'images/logo-elastomeros-icon.svg' %}" rel="icon" />
    {% block css %}
      {% include "partials/styles.html" %}
    {% endblock css %}
    {% block extra_css %}
    {% endblock extra_css %}
    {% htmx_script %}
  </head>
  <body {% block body_attributes %}
        {% endblock body_attributes %}
        hx-headers='{"x-csrftoken": "{{ csrf_token }}"}'>
    {% block body %}
      <main class="page-wrapper">
        {% block main %}
          {% block header %}
            {% include "partials/header.html" %}
          {% endblock header %}
          {% block content %}
          {% endblock content %}
        {% endblock main %}
      </main>
      {% block footer %}
        {% include "partials/footer.html" %}
      {% endblock footer %}
      <a href="#top" class="btn-scroll-top" data-scroll>
        <svg viewBox="0 0 40 40"
             fill="currentColor"
             xmlns="http://www.w3.org/2000/svg">
          <circle cx="20"
                  cy="20"
                  r="19"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-miterlimit="10" />
        </svg>
        <i class="ai-arrow-up"></i>
      </a>
    {% endblock body %}
    {% block offcanvas %}
    {% endblock offcanvas %}
    {% block modals %}
    {% endblock modals %}
    {% block js %}
      {% include "partials/scripts.html" %}
    {% endblock js %}
    {% block extra_js %}
    {% endblock extra_js %}
    {% block messages %}
      {% include "partials/messages.html" %}
    {% endblock messages %}
  </body>
</html>